apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: gitops-agent-secret
    app.kubernetes.io/part-of: argocd
  name: {{ .Values.cluster.name }}-agent
  namespace: argocd
type: Opaque
stringData:
  GITOPS_AGENT_TOKEN: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURTcjJUUEg3NkRsSzgrClNhejFTZ05yQmtMTFZUc3V4ak5KOHlPZGw2Q0g1bVNnMENtRzk5U2JwaE9yNWVud3dHMmZud0N0SXVRdXFhQ3YKUFZ2eXJpeWtkbUcxbk02eU1NODJPUE40S1A0T3J6VzB6Y2lla2tuM3dQQ0U3ZDB6OU9sa1FYSEw5ZXBSV3FuQwplc0NpZ2QySVlDWDU3RTdHaXNUMlNwbmgrRGR5RWIzWTdmcWxCY29MaGhuUzZSOWRrbGl4c1BJVlNKZ0NzanZoCkd5WllJZ3U1RTV0SWtMV1phTExaaHpaRnZEdDluUEx3bGxPQ202ZHkxK2xxaWJZOTRKeUdqNUtTK291S2Z0ZysKYWNiY0VDUkpjVHVYbkwxNDE0c3Uzc1ZmSDJ2V3lIUG9EUlI2cGo1SjdNdnZCVlk3b1dkMXBYaFFZaFpNVE5IQwo0NjMrTzdJcEFnTUJBQUVDZ2dFQWJXTnBtT3puY3RRQkJQc2wxUmwvbXRMZVhVbzhkeldyTFlzVEErRFZGWnAyCnh0UXRxNGtEbDJqc0w4VW82THBRY0o4U3I5STgzVWx2UjIwNVQxQkZsNEpyaXVzR21wZ2pEZ2tWeUY2b1FpR1EKWmZhdVlqNmNMd203RjVtVXowUXE1Y1hnK3NBTXovNmR3MzhPZzVHZjN3M2t5ZFY2dFRVWnZMTFJJUFZLZkd0dQppdGtRWGxGeFJ6Y0k5UHlPM1h0aHpwKzNxRlZEQWhlVVd2OUhGL0t6NmUzR2NxSHdUZjV2aVdCTFBmQmlYb2pyClJmdUp2cUUyVUNyZXZnQ25kSmV0b2RjSEFRZ1d4TmtXaUhhN0lTQzFPb3RZUlNYVGZXdlB4bHloRzAyUTZqZXMKRmYva3d4Y1Y3TmxKWEVadXBXV0lEc0NtanB0cjNJSFpoTTNYMmxkVzdRS0JnUURqZ0J5RmpQWTVFK3lrS2p1ZApQS2d6N3N4RDRBN3JkOXZZb2M4YlFZUm42ekRHb1l3RkhxOVduTjA2QThQakd2R0hmQ1dYYTRqUnJzMUdPYzBOCnQ3R2FSblA5aGpxNHBRb2VHUjM3V3lhNDRhQ3g2WHFQaUJ2aDZhOE5JL1hvSVlkdkk1OENKemw4ZkNvNG9nWHIKK0JmYlJ3anBtbTN4M24wR0hQazJuWVFOTXdLQmdRRHRGQVR5T0k1Uy9kOGo4R3pISEZTN3hZMTVab2pWUWFybwpDQlhXRllMby9oZFBzK05VdDI3QS8vR1E5T2tNTzlxaGVVODRTU2hNd096cnFpUEJpNVdlaCtnT0xUd2N6S3pDClFtTWcwQmpoMmtXWXE3UGxaN0Q5MHlwcGY3UUJHR0xKL3lhS1lLTWJNcDRmYlpjL0JUZ2w2ZktFbHZ6RXBndEcKamJmQTMzU3JNd0tCZ0RaeW9lRGd0TWxDV0grTjBBaTR6TFRwTVNBSmp1aVNIaDdCMHpSOXdMZXlWVkVrdHNNKwo3YzMzNndhSWdpaG5lV2pvc0lLRjdRL3FHeHowbG52eSsrR2xmUHN2VmZ4OUcyZktzUjlJV0lNbEZQV2ZvSUtiCm03aTgyZlYySnROd3V0NUJrenZMc1hsMnFoQTF6dDhEMkluVmZXK1RVejd3OWRFeHUvOXpRWGg3QW9HQkFKYWcKdkkvRlBUQWZtckd6NVBrUTJBbEJlQ1NrNzlWRzFyWjd4SnZ6cU93dDNGUElnR3huNjFkMmhsM0tMWE9YWjg1bQpTOTRBSlRtMjdoREJWZHgzdWtVeUprOHprRmpmOWZlcXhGNnB1TlZ1bi85alFIWkZ6bDlHMWxDWFVaL01oWisvCm5CWVpWaWhHbmM1c0M4ZC9vbS84VnhqRThhNWpyUkJUcEdkSDBsR2ZBb0dBS3pUeGtoM0c0Smo0S2pTYm12eXgKNE0ra285VHFOMndSK3BPekUzZlNtTzJ1TmpCV3Z4UDJjSlpyd1pQcVRkVmNFQjVSdC8veWNYRVVZV3I0bjhxTwplOTB1MHlMUUV3b3ZkMnRYaWdEUmFwNlJRdVFyTGtJdGI0aS9zcHFRbTR5V1RqTDk1SFlFRjR2VGM5eEFXTVdpCmZhaE5laXAxQjByc2NnZ0JwQUgrRzYwPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---


